#!/bin/sh
#
# @name VTOL Bicopter
#
# @type VTOL Bicopter
#

sh /etc/init.d/rc.bicopter_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_ROLLRATE_P 0.05
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.15

	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0

	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 0
	param set MAV_PROTO_VER 2

	param set COM_DISARM_LAND -1
	param set MPC_MAX_THRUST 29.4

	param set MPC_LQR_K11 	 4.935986
	param set MPC_LQR_K12 	 -0.000000
	param set MPC_LQR_K13 	 -0.000000
	param set MPC_LQR_K14 	 4.242641
	param set MPC_LQR_K15 	 -0.000000
	param set MPC_LQR_K16 	 0.000000
	param set MPC_LQR_K17 	 -0.897757
	param set MPC_LQR_K18 	 0.000000
	param set MPC_LQR_K19 	 -4.148507
	param set MPC_LQR_K110 	 -8.230421
	param set MPC_LQR_K111 	 0.000000
	param set MPC_LQR_K112 	 -41.620430
	param set MPC_LQR_K21 	 0.000000
	param set MPC_LQR_K22 	 4.935986
	param set MPC_LQR_K23 	 0.000000
	param set MPC_LQR_K24 	 0.000000
	param set MPC_LQR_K25 	 4.242641
	param set MPC_LQR_K26 	 0.000000
	param set MPC_LQR_K27 	 -0.000000
	param set MPC_LQR_K28 	 -10.165720
	param set MPC_LQR_K29 	 -0.000000
	param set MPC_LQR_K210 	 -0.000000
	param set MPC_LQR_K211 	 -42.426407
	param set MPC_LQR_K212 	 -0.000000
	param set MPC_LQR_K31 	 0.000000
	param set MPC_LQR_K32 	 -0.000000
	param set MPC_LQR_K33 	 13.244572
	param set MPC_LQR_K34 	 -0.000000
	param set MPC_LQR_K35 	 0.000000
	param set MPC_LQR_K36 	 12.515790
	param set MPC_LQR_K37 	 8.283247
	param set MPC_LQR_K38 	 -0.000000
	param set MPC_LQR_K39 	 -1.409703
	param set MPC_LQR_K310 	 122.780268
	param set MPC_LQR_K311 	 -0.000000
	param set MPC_LQR_K312 	 -24.279741
	param set MPC_LQR_K41 	 4.935986
	param set MPC_LQR_K42 	 0.000000
	param set MPC_LQR_K43 	 0.000000
	param set MPC_LQR_K44 	 4.242641
	param set MPC_LQR_K45 	 0.000000
	param set MPC_LQR_K46 	 -0.000000
	param set MPC_LQR_K47 	 0.897757
	param set MPC_LQR_K48 	 -0.000000
	param set MPC_LQR_K49 	 4.148507
	param set MPC_LQR_K410 	 8.230421
	param set MPC_LQR_K411 	 -0.000000
	param set MPC_LQR_K412 	 41.620430
	param set MPC_LQR_K51 	 -0.000000
	param set MPC_LQR_K52 	 4.935986
	param set MPC_LQR_K53 	 0.000000
	param set MPC_LQR_K54 	 -0.000000
	param set MPC_LQR_K55 	 4.242641
	param set MPC_LQR_K56 	 0.000000
	param set MPC_LQR_K57 	 0.000000
	param set MPC_LQR_K58 	 10.165720
	param set MPC_LQR_K59 	 -0.000000
	param set MPC_LQR_K510 	 0.000000
	param set MPC_LQR_K511 	 42.426407
	param set MPC_LQR_K512 	 -0.000000
	param set MPC_LQR_K61 	 0.000000
	param set MPC_LQR_K62 	 0.000000
	param set MPC_LQR_K63 	 13.244572
	param set MPC_LQR_K64 	 0.000000
	param set MPC_LQR_K65 	 -0.000000
	param set MPC_LQR_K66 	 12.515790
	param set MPC_LQR_K67 	 -8.283247
	param set MPC_LQR_K68 	 0.000000
	param set MPC_LQR_K69 	 1.409703
	param set MPC_LQR_K610 	 -122.780268
	param set MPC_LQR_K611 	 0.000000
	param set MPC_LQR_K612 	 24.279741
fi

set MAV_TYPE 2

set MIXER_FILE etc/mixers-sitl/bicopter_sitl.main.mix
set MIXER custom
