#!/bin/sh
#
# @name VTOL Bicopter
#
# @type VTOL Bicopter
#

sh /etc/init.d/rc.bicopter_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_ROLLRATE_P 0.05
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.15

	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0

	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 0
	param set MAV_PROTO_VER 2
fi

set MAV_TYPE 23

set MIXER_FILE etc/mixers-sitl/bicopter_sitl.main.mix
set MIXER custom
